server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ruralflow
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never

logging.level.com.agriroute=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.internal-api-key=${INTERNAL_API_KEY:ela-internal-dev-key-2026}
