# ELA Cognitive Memory Record & Provenance Contract (Phase 12.2)
from typing import Dict, Any, Optional, List, Literal
from pydantic import BaseModel, Field
from datetime import datetime, timezone
import uuid

MemoryCategory = Literal[
    "EPISODIC",      # What happened in previous interactions / dialogue turns
    "SEMANTIC",      # Stable learned facts / user preferences appropriate to retain
    "GOAL",          # Active objectives and their current execution state
    "DECISION",      # Key decisions, recommendations, and their rationale/provenance
    "OUTCOME",       # Verified results of previous actions (from Java/execution)
    "OPERATIONAL",   # Current/recent AgriRoute state (corridor delays, market prices)
    "CONSTRAINT",    # User or system constraints (budget, vehicle, time limits)
    "WARNING",       # Previous failures, risks, or unresolved operational issues
]

MemoryProvenance = Literal[
    "USER_STATED",      # Directly stated by the authenticated user
    "SYSTEM_OBSERVED",  # Observed by platform services (e.g. tracking telemetry)
    "JAVA_VERIFIED",    # Authoritatively verified by Spring Boot backend
    "MODEL_INFERENCE",  # Predicted by ML / neural models (NOT automatic fact)
    "AGENT_OUTPUT",     # Generated by specialized multi-agent workers
    "LEARNING_EVENT",   # Extracted from governed continuous learning events
    "SYNTHETIC_TEST",   # Benchmark synthetic test data (strictly non-operational)
]

EvidenceClass = Literal[
    "VERIFIED",    # Absolute ground truth (Java verified, completed action)
    "USER_STATED", # Explicit user preference or constraint
    "OBSERVED",    # Live sensor/system telemetry
    "PREDICTED",   # ML forecast (subject to uncertainty)
    "INFERRED",    # Deductions made from conversational context
    "SYNTHETIC",   # Synthetic test artifact
]

MemorySensitivity = Literal["PUBLIC", "OPERATIONAL", "CONFIDENTIAL", "RESTRICTED"]
RetentionPolicy = Literal["TRANSIENT_SESSION", "ACTIVE_GOAL", "LONG_TERM_USER", "PERMANENT_AUDIT"]
MemoryStatus = Literal["ACTIVE", "SUPERSEDED", "INVALIDATED", "EXPIRED", "ARCHIVED"]


EVIDENCE_WEIGHTS: Dict[EvidenceClass, float] = {
    "VERIFIED": 1.0,
    "USER_STATED": 0.95,
    "OBSERVED": 0.90,
    "PREDICTED": 0.70,
    "INFERRED": 0.60,
    "SYNTHETIC": 0.50,
}


class ElaMemoryRecord(BaseModel):
    """
    Strongly typed cognitive memory record.
    Carries provenance, evidentiary weight, retention policy, and lifecycle status.
    """
    memory_id: str = Field(default_factory=lambda: f"mem-{uuid.uuid4().hex[:10]}")
    session_id: str
    user_id: Optional[str] = None
    goal_id: Optional[str] = None
    memory_type: MemoryCategory
    content: str
    structured_data: Dict[str, Any] = Field(default_factory=dict)
    source: str = "user_interaction"
    provenance: MemoryProvenance = "USER_STATED"
    evidence_class: EvidenceClass = "USER_STATED"
    confidence: float = 1.0
    importance: float = 0.5  # 0.0 (trivial) to 1.0 (critical decision/constraint)
    sensitivity: MemorySensitivity = "OPERATIONAL"
    retention_policy: RetentionPolicy = "ACTIVE_GOAL"
    status: MemoryStatus = "ACTIVE"
    superseded_by: Optional[str] = None
    invalidation_reason: Optional[str] = None
    ttl_seconds: Optional[int] = None  # Freshness TTL
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    expires_at: Optional[str] = None

    @property
    def evidence_weight(self) -> float:
        return EVIDENCE_WEIGHTS.get(self.evidence_class, 0.5)

    def is_stale(self, reference_time: Optional[datetime] = None) -> bool:
        """Determines if the memory has exceeded its TTL or explicit expiration."""
        if self.status in ["SUPERSEDED", "INVALIDATED", "EXPIRED", "ARCHIVED"]:
            return True
        if not self.expires_at:
            return False
        ref = reference_time or datetime.now(timezone.utc)
        try:
            exp = datetime.fromisoformat(self.expires_at)
            if exp.tzinfo is None:
                exp = exp.replace(tzinfo=timezone.utc)
            return ref > exp
        except Exception:
            return False

    def mark_superseded(self, newer_memory_id: str):
        self.status = "SUPERSEDED"
        self.superseded_by = newer_memory_id
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def mark_invalidated(self, reason: str):
        self.status = "INVALIDATED"
        self.invalidation_reason = reason
        self.updated_at = datetime.now(timezone.utc).isoformat()

    def mark_expired(self):
        self.status = "EXPIRED"
        self.updated_at = datetime.now(timezone.utc).isoformat()
